JobSubmissionPlatform/urls.py
from django.contrib import admin
from django.urls import path, re_path,include
from django.views.static import serve
from django.conf import settings
from app1 import views
from app1.views import Inform, Students_view, Class, Community,upload,account,ShowMe

urlpatterns = [
    #这个是media的文件的固定要求
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    # path('login/')

    # 作业提交模块(学委查看页面)
    path('Inform/Homework/', Inform.Inform_list),
    path('Inform/add/', Inform.Inform_add),
    path('Inform/delete/', Inform.Inform_delete),
    path('Inform/detail/', Inform.Inform_detail),
    path('Inform/edit/', Inform.Inform_edit),
    path('Inform/multi/', Inform.Inform_multi),

    # 饼图的制作----先拿class页面进行设置
    path('Inform/pie/', Inform.Inform_pie),

    # 学生所能查看的页面以及设置--
    path('Students_view/Homework/', Students_view.View_add),
    path('Students_view/MyInform/', Students_view.View_My),
    path('Students_view/AddPortal/', Students_view.AddPortal),



    #这个是为了展现课表

    path('ShowMe/BasicInfor/',ShowMe.BasicInform),

    # 用户的登录管理
    path('login/', account.login),
    path('logout/',account.logout),

    # 照片
    path('image/code/', account.image_code),

    #班级列表
    path('Class/list/', Class.Class_list),
    path('Class/add/', Class.Class_add),

    #注意在使用删除，修改等操作时候，非ajax请求时，请注意要携带nid，否则报找不到路由

    # 社团活动
    path('Community/list/', Community.Community_list),
    path('Community/add/', Community.Community_add),
    path('Community/<int:nid>/delete/', Community.Community_delete),

    #这个对应的是引入model来进行数据提交的数据库
    path('upload/model/form/', upload.upload_modal_form),

]

app1/models.py
from django.db import models

# Create your models here.
class Class_list(models.Model):
    """班级表---范围更大一些"""
    name=models.CharField(verbose_name="姓名",max_length=32)
    schoolID= models.CharField(verbose_name="学号", max_length=64)
    className=models.CharField(verbose_name="所在班级",max_length=32)
    bedroom = models.CharField(verbose_name="寝室", max_length=32)
    QQID = models.CharField(verbose_name="QQ", max_length=64)
    phoneID = models.CharField(verbose_name="微信", max_length=64)

    def __str__(self):
        return self.className

"""问题！！！！！数据库的时间需要去进行更改"""

class UserInfo(models.Model):
    """用户使用学号来进行登录--范围小一些"""
    name = models.CharField(verbose_name="姓名", max_length=16)
    password = models.CharField(verbose_name="密码", max_length=64)
"""目前这个仅仅是为了我进行测试去写的测试"""
class stuLogin(models.Model):
    name = models.CharField(verbose_name="用户名",max_length=16)
    password = models.CharField(verbose_name="密码",max_length=64)
class teacher(models.Model):
    name = models.CharField(verbose_name="用户名",max_length=16)
    password = models.CharField(verbose_name="密码",max_length=64)



class Work_inform(models.Model):
    """作业通知表"""
    inform=models.CharField(verbose_name="通知",max_length=32)
    create_time = models.DateField(verbose_name="通知时间")
    level_choices = (
        (1, "正常作业"),
        (2, "一般提醒"),
        (3, "紧急通知"),
        (4, "紧急注意")
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)


class StuInfo(models.Model):
    """学生信息表"""
    username = models.CharField(verbose_name="网名", max_length=16)
    Stu_num = models.CharField(verbose_name="学号", max_length=64)
    password=models.CharField(verbose_name='密码',max_length=32)

    gender_choices = (
        (1, "男"),
        (2, "女"),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)
    def __str__(self):
        return self.username

# img = models.FileField(verbose_name="Logo", max_length=128, upload_to='Community/')
class CommunityActive(models.Model):

    """社团活动"""
    title=models.CharField(verbose_name="主题",max_length=64)
    content=models.CharField(verbose_name="内容",max_length=128)
    place=models.CharField(verbose_name="地点",max_length=64)
    hold_time = models.DateField(verbose_name="举办时间")
    img = models.FileField(verbose_name="Logo", max_length=128, upload_to='Community/')
    active_types=(
        (1,"社团招新"),
        (2, "举办活动"),
        (3, "志愿参与"),
    )
    active=models.SmallIntegerField(verbose_name="活动类型",choices=active_types)

class Boss(models.Model):
    """老板"""
    name=models.CharField(verbose_name="姓名",max_length=32)
    age = models.IntegerField(verbose_name="年龄")
    img = models.CharField(verbose_name="头像", max_length=128)
class City(models.Model):
    """ 城市 """
    name = models.CharField(verbose_name="名称", max_length=32)
    count = models.IntegerField(verbose_name="人口")
    # 本质上数据库也是CharField，自动保存数据。
    img = models.FileField(verbose_name="Logo", max_length=128, upload_to='city/')

app1/views/Class.py
from django.shortcuts import HttpResponse,redirect,render
from django.views.decorators.csrf import csrf_exempt
from app1.utils.bootstrap import BootStrapModelForm
from django.http import JsonResponse
from app1 import models
from openpyxl import load_workbook
from datetime import datetime
class InformModelForm(BootStrapModelForm):
    class Meta:
        model = models.Class_list
        fields = "__all__"
def Class_list(request):
    # 到时候可以按照学号列表来进行排列
    queryset = models.Class_list.objects.all()
    form = InformModelForm()
    context = {
        "form": form,
        "queryset": queryset
    }
    return render(request, 'Class_Information.html', context)
@csrf_exempt
def Class_add(request):
    """添加同学"""
    form = InformModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({"status": True, "error": form.errors})

app1/views/Community.py
from django.shortcuts import HttpResponse,redirect,render
from django.views.decorators.csrf import csrf_exempt
from app1.utils.bootstrap import BootStrapModelForm
from django.http import JsonResponse
from app1 import models
class UpModelForm(BootStrapModelForm):
    bootstrap_exclude_fields = ['img']
    class Meta:
        model =models.CommunityActive
        fields="__all__"
def Community_list(request):
    # 到时候可以按照学号列表来进行排列
    queryset = models.CommunityActive.objects.all()
    form = UpModelForm()
    context = {
        "form": form,
        "queryset": queryset
    }
    return render(request, 'Community.html', context)
def Community_add(request):
    """使用modelForm来进行图片的保存，上传"""
    title = "ModelForm上传文件"
    if request.method == "GET":
        form = UpModelForm()
        return render(request, 'Community.html', {"form": form, 'title': title})

    form = UpModelForm(data=request.POST, files=request.FILES)
    if form.is_valid():
        form.save()
        return HttpResponse("上传成功")
    return render(request, 'Community.html', {"form": form, 'title': title})
def Community_delete(request,nid):
    """进行数据的删除"""
    models.CommunityActive.objects.filter(id=nid).delete()
    return redirect("/Community/list/")

app1/views/Inform.py
from django.shortcuts import render, HttpResponse, redirect
from django.views.decorators.csrf import csrf_exempt
from app1.utils.bootstrap import BootStrapModelForm
from django.http import JsonResponse
from app1 import models
from openpyxl import load_workbook
from datetime import datetime
import random
class InformModelForm(BootStrapModelForm):
    class Meta:
        model = models.Work_inform
        fields = "__all__"
        exclude = ["create_time"]  # 将这个内容不显示
def Inform_list(request):
    # 按照时间顺序来进行最新数据输出
    queryset = models.Work_inform.objects.all().order_by("-id")

    form = InformModelForm()
    context = {
        "form": form,
        "queryset": queryset
    }
    return render(request, 'Inform_Homework.html', context)
# 上边俩是将数据显示在数据库中
@csrf_exempt
def Inform_add(request):
    """新建订单"""
    form = InformModelForm(data=request.POST)
    if form.is_valid():
        # 下面的那个是自动生成的数然后填充进去的数值
        # 随机函数获取今日时间，然后添加到数据中
        form.instance.create_time = datetime.now().strftime("%Y-%m-%d")
        # 去找到登录的这个账户的管理员，然后来进行控制
        # form.instance.admin_id = request.session["info"]["id"]
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({"status": True, "error": form.errors})
def Inform_delete(request):
    """删除订单"""
    uid = request.GET.get("uid")
    exists = models.Work_inform.objects.filter(id=uid).exists()
    if not exists:
        return JsonResponse({"status": False, 'error': "获取失败,数据不存在"})
    models.Work_inform.objects.filter(id=uid).delete()
    return JsonResponse({"status": True})
def Inform_detail(request):
    uid = request.GET.get("uid")
    row_dict = models.Work_inform.objects.filter(id=uid).values("inform").first()
    if not row_dict:
        return JsonResponse({"status": False, 'error': "数据不存在"})
    result = {
        "status": True,
        "data": row_dict
    }
    return JsonResponse(result)
# 对编辑页面的重新规划
@csrf_exempt
def Inform_edit(request):
    """编辑页面"""
    uid = request.GET.get("uid")
    row_object = models.Work_inform.objects.filter(id=uid).first()
    if not row_object:
        return JsonResponse({"status": False, 'tips': "数据不存在"})
    form = InformModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({"status": True, "error": form.errors})
#饼状图的展示
def Inform_pie(request):
    """饼状图"""
    db_data_list = [
        {"value": 2048, "name": '已交'},
        {"value": 735, "name": '未交'},
        {"value": 1580, "name": '展示'},
    ]

    result = {
        "status": True,
        "data": db_data_list,
    }
    return JsonResponse(result)

#采用表格的形式去进行作业的提交
def Inform_multi(request):
    """批量上传excel文件"""
    # 1首先获取文件的对象
    file_objects = request.FILES.get("exc")
    # print(file_objects.name) #获取文件的名字

    wb = load_workbook(file_objects)
    sheet = wb.worksheets[0]
    dayTime = datetime.now().strftime("%Y-%m-%d")
    for row in sheet.iter_rows(min_row=2):
        text = row[0].value
        text2= row[1].value
        print("{}--{}".format(text,text2))
        exist = models.Work_inform.objects.filter(inform=text).exists()
        if not exist:
            models.Work_inform.objects.create(inform=text, level=text2, create_time=datetime.now())
            print("{}-{}-{}".format(text,text2,datetime.now()))
        else:
            return  HttpResponse("重复上传或格式不正确，请重新提交")
    return redirect("/Inform/Homework/")

app1/views/ShowMe.py
from urllib import request

from django.shortcuts import render,HttpResponse,redirect
from api.napi import Info
from app1.views.account import LoginForm
from api.news_api import SchoolNews
from api.MessagePort import MessageLoginPortal

def BasicInform(request):
    info = request.session["info"]
    IF = Info(cookies=info)
    MyInform = IF.getPersonInfo()
    MyDatas = MyInform['data']
    me=IF.getCollegesList()
    CollageLists=IF. getTeachingPlanCollegesList()
    classPlans= IF.getMajorList(college_id="2021")
    form = LoginForm()
    #校园新闻
    News=SchoolNews()
    news=News.getNewsListByCat('10307',1)
    newsList = news['data']
    context = {
        'title':"校园新闻",
        # "queryset":news,
        'Me': me,
        "queryset":newsList,
        'info111':MyDatas,
        'CollageLists':CollageLists,
        'classPlans':classPlans,
        'form':form
    }
    return render(request,'ShowMe.html',context)

app1/views/Students_view.py
from django.shortcuts import render,HttpResponse,redirect
from django.http import JsonResponse
from django import forms
from app1.utils.bootstrap import BootStrapModelForm, BootStrapForm
from app1 import  models
from app1.views.account import  Login_test
from api.napi import Login, Info
from api.news_api import SchoolNews
from api.MessagePort import MessageLoginPortal
# Create your views here.
class LoginForm(BootStrapForm):
    username=forms.CharField(
        label="用户名",
        widget=forms.TextInput,
        required=True
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput,
        required=True
    )
#实现教务系统的登录
class LoginPortal(object):
    def __init__(self, username, password):
        self.username = username
        self.password = password
    def login_potral(self):
        LGP = MessageLoginPortal()
        result = LGP.login(f'{self.username}', f'{self.password}')
        return result


class InformModelForm(BootStrapModelForm):
    class Meta:
        model = models.Work_inform
        fields = "__all__"
        exclude = ["create_time"]  # 将这个内容不显示
def View_add(request):
    form = InformModelForm(data=request.POST)
    if form.is_valid():
    #     # print(form.cleaned_data) #来显示提交的信息
        username=form.cleaned_data['username']
        password=form.cleaned_data['password']
        LG=LoginPortal(username=username,password=password) #用作登录
        back=LG.login_potral()

        if back['code'] != 1000:
            form.add_error("password", "用户名或密码错误")
            # return render(request, 'login.html', {"form": form})
        request.session["info111"] = back['data']['cookies']  # 教务系统
    context = {
        'title': "这个是新的页面哎",
    }
    return render(request, 'ShowMe.html',context)
def View_My(request):
    info = request.session["info"] #保存的cookie值，这样就可以去进行其他页面的数据加载了
    IF=Info(cookies=info)
    MyInform=IF.getPersonInfo()
    MyDatas=MyInform['data']
    Me=MyInform['data']['name']
    # SchoolID=MyInform['data']['studentId']
#后续进行添加，做成可交互式的，就是可以选择的那种类型
    News=SchoolNews()
    news=News.getNewsListByCat('10307',1)
    news=news['data']
    form = LoginForm()
    context = {
        "MyInform":  MyInform,
        'title':"校园新闻",
        "queryset":news,
        'MeInform':Me,
        'MyDatas':MyDatas,
        "form": form
    }
    return render(request,'Students_view.html',context)
def AddPortal(request):
    pass

app1/views/account.py
from django.shortcuts import render, HttpResponse, redirect
from django import forms
# 引入教务系统的爬虫
from api.napi import Login, Info
from io import BytesIO
from app1.utils.bootstrap import BootStrapForm
from app1.utils.bootstrap import BootStrapModelForm
from app1.utils.encrypt import md5  # 这个是没有用上的
from app1 import models
from app1.utils.code import check_code


class LoginForm(BootStrapForm):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput,
        required=True
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput,
        required=True
    )
    code = forms.CharField(
        label="验证码",
        widget=forms.TextInput,
        required=True
    )


# 这个是经过加密，先进行取消，到时候进行两种形式的，先加密再解密
# def clean_password(self):
#     pwd=md5(self.cleaned_data.get("password"))
#     return pwd
# 一会来进行设置两个登录的方式，教务系统和那个管理员
def login(request):
    """登录页面"""
    if request.method == "GET":
        form = LoginForm()
        return render(request, 'login.html', {"form": form})
    form = LoginForm(data=request.POST)
    if form.is_valid():
        # print(form.cleaned_data) #来显示提交的信息
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']

        LG = Login_test(username=username, password=password)  # 用作登录
        data = LG.login_test1()

        user_input_code = form.cleaned_data.pop('code')
        code = request.session.get('image_code', '')
        if code.upper() != user_input_code.upper():
            form.add_error("code", '验证码错误')
            return render(request, 'login.html', {"form": form})

        # 这个是用教务系统进行登录
        if data['code'] != 1000:
            form.add_error("password", "用户名或密码错误")
            return render(request, 'login.html', {"form": form})

        # 存储教务系统的cookie值
        request.session["info"] = data['data']['cookies']  # 教务系统

        # global sharedata #先声明是全局变量，然后再进行赋值
        # sharedata = f"{request.session['info']}"
        # # print(sharedata)

        # request.session["info"]={"id":admin_object.id,"name":admin_object.username} #数据库

        request.session.set_expiry(60 * 60 * 24 * 7)
        # 这个是相当于自己去设置Sessionid

        # 在这先暂时去找一个返回的页面--登录成功的
        return redirect("/Inform/Homework/")
    return render(request, 'login.html', {"form": form})


"""这个是引入教务系统的登录"""
class Login_test(object):
    def __init__(self, username, password):
        self.username = username
        self.password = password

    def login_test1(self):
        LG = Login()
        result = LG.login(f'{self.username}', f'{self.password}')
        if result['code'] == 1000:
            user = models.UserInfo.objects.filter(name=self.username).first()
            if user:
                user.password = self.password
                user.save()
            else:
                new_user = models.UserInfo(name=self.username, password=self.password)
                new_user.save()

        return result

    # def get_shared_data(self):
    #     """将获取的cookie值来传递给其他的，避免再次登录"""
    #     global sharedata
    #     sharedata = self.shared_value
    #     return  sharedata


def image_code(request):
    """生成验证图片"""
    img, code_string = check_code()
    # 写入到自己的session文件中
    request.session['image_code'] = code_string
    # 对于session来进行60S的超时校验
    request.session.set_expiry(60)

    # print(code_string)
    stream = BytesIO()
    img.save(stream, 'png')

    return HttpResponse(stream.getvalue())


def logout(request):
    """ 注销 """
    request.session.clear()
    return redirect('/login/')

app1/templates/Class_Information.html
{% extends 'ParentTemplate.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                班级列表
                <input  id="btnAdd" style="border-radius: 4px; " class="btn-info" value="新 增" type="button">
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>学号</th>
                    <th>寝室</th>
                    <th>QQ</th>
                    <th>手机号</th>
                    <th>操作</th>

                </tr>
                </thead>
                <tbody>
                <tr>
                    {% for obj in queryset %}
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.schoolID }}</td>
                        <td>{{ obj.bedroom }}</td>
                        <td>{{ obj.QQID }}</td>
                        <td>{{ obj.phoneID }}</td>


                        <td>
                            <input  style="border-radius: 3px; font-size: 12px; " class="btn-danger btn-delete"
                                   value="删 除" type="button">
                            <input  style="border-radius: 3px; font-size: 12px; " class="btn-primary  btn-edit"
                                   value="编 辑" type="button">
{#                            <input style="border-radius: 3px; font-size: 12px;" id="btnAdd" class="btn-info"#}
{#                                   value="添 加" type="button">#}
                        </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {#    进行同学的添加#}
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel"></h4>
                </div>
                <div class="modal-body">
                    <form id="formAdd">
                        <div class="clearfix">
                            {% for field in form %}
                                <div class="col-lg-6">
                                    <div class="form-group" style="position: relative;">
                                        <label>{{ field.label }}</label>
                                        {{ field }}
                                        <span class="errors_msg" style="color: #b92c28;position: absolute"></span>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                    <button id="btnSave" type="button" class="btn btn-primary">保 存</button>
                </div>
            </div>
        </div>
    </div>


{% endblock %}
{% block js %}
    <script src="{% static '/js/echarts.min.js' %}"></script>
    <script type="text/javascript">
        var DELETE_ID;
        var EDIT_ID;
        $(function () {
            bindBtnAddEvent();
            bindBtnSaveEvent();
        })
         function bindBtnAddEvent() {
            $("#btnAdd").click(function () {
                 EDIT_ID = undefined;
                $("#dformAd")[0].reset();
                $(".modal-title").text("添加人员");
                $('#myModal').modal('show');
            });
        }
         function bindBtnSaveEvent() {
            $("#btnSave").click(function () {
                $(".errors_msg").empty();
                if (EDIT_ID) {

                    {#doEdit();#}
                } else {
                    doAdd();
                }

            });
        }

        function doAdd() {
            $.ajax({
                url: "#",
                type: "post",
                data: $("#formAdd").serialize(),
                dataType: "JSON",
                success: function (res) {
                    {#console.log(res);#}
                    if (res.status) {
                        alert("创建成功");
                        location.reload();
                        $("#formAdd")[0].reset();
                        $('#myModal').modal('hide');

                    }
                }
            })
        }
    </script>

{% endblock %}

app1/templates/Community.html
{% extends 'ParentTemplate.html' %}
{% load static %}
{% block content %}

    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                社团情况
                <input id="btnAdd" style="border-radius: 4px; " class="btn-info" value="新 增" type="button">
                <a href="/upload/model/form/">新增</a>
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>主题</th>
                    <th>内容</th>
                    <th>时间</th>
                    <th>类型</th>
                    <th>地点</th>
                    <th>海报</th>
                    <th>操作</th>

                </tr>
                </thead>
                <tbody>
                <tr>
                    {% for obj in queryset %}
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.title }}</td>
                        <td>{{ obj.content }}</td>
                        <td>{{ obj.hold_time }}</td>
{#                        有关选项的可以使用get_XX_display#}
                        <td>{{ obj.get_active_display }}</td>
                        <td>{{ obj.place }}</td>
                        <td><img src="/media/{{ obj.img }} " style="width: 50px;height: 30px"></td>
                        {#                        <img src="/media/{{ obj.img }} " style="width: 50px;height: 30px">#}
                        <td>
                            <a class="btn btn-danger btn-xs" href="/Community/{{ obj.id }}/delete/">删 除</a>
                            <a class="btn btn-danger btn-xs" href="/admin/{{ obj.id }}/delete/">编 辑</a>
                        </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

app1/templates/PinPage.html
{% extends 'ParentTemplate.html' %}
{% block content %}



{% endblock %}

app1/templates/ShowMe.html
{% extends 'Students_view.html' %}
{% load static %}
{% block content1 %}
<div class="">
 <div class="panel panel-default">
            <div class="panel-heading">
                 {{ CollageLists }}
            </div>
        </div>
</div >
     <div class="panel panel-default">
            <div class="panel-heading">
                 {{ classPlans }}
            </div>
        </div>
{#  这个是存在问题的-不能进行封闭  </div >#}
{% endblock %}
{% block js %}
{% endblock %}

app1/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户登录</title>
     <link rel="stylesheet" href="{% static '/plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;
            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>用户登录</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputEmail1">用户名</label>
            {{ form.username }}
            <span>{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">密码</label>
            {{ form.password }}
            <span style="color: red">{{ form.password.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label for="id_code">图片验证码</label>
            <div class="row">
                <div class="col-lg-7">
                   {{ form.code }}
                    <span style="color: #b92c28">{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-lg-5">
                    <img id="image_code" src="/image/code/" style="width: 125px">
                </div>
            </div>
        </div>
        <input type="submit" value="登 录" class="btn btn-primary">
    </form>
</div>
</body>
</html>

app1/templates/upload_form.html
{% extends 'ParentTemplate.html' %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> {{ title }} </h3>
            </div>
            <div class="panel-body">
                <form method="post" enctype="multipart/form-data" novalidate >
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style=" color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}